<?php

namespace ContainerHV3z5J9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tpwd01HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tpwd01H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tpwd01H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.aJomXdb', 'get_ServiceLocator_AJomXdbService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.Mwctkz4', 'get_ServiceLocator_Mwctkz4Service', true],
            'App\\Controller\\SpiceGirlsController::add' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\SpiceGirlsController::edit' => ['privates', '.service_locator.jigvWSH', 'get_ServiceLocator_JigvWSHService', true],
            'App\\Controller\\SpiceGirlsController::index' => ['privates', '.service_locator.CxDYfi9', 'get_ServiceLocator_CxDYfi9Service', true],
            'App\\Controller\\SpiceGirlsController::offer' => ['privates', '.service_locator.jigvWSH', 'get_ServiceLocator_JigvWSHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.aJomXdb', 'get_ServiceLocator_AJomXdbService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.Mwctkz4', 'get_ServiceLocator_Mwctkz4Service', true],
            'App\\Controller\\SpiceGirlsController:add' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\SpiceGirlsController:edit' => ['privates', '.service_locator.jigvWSH', 'get_ServiceLocator_JigvWSHService', true],
            'App\\Controller\\SpiceGirlsController:index' => ['privates', '.service_locator.CxDYfi9', 'get_ServiceLocator_CxDYfi9Service', true],
            'App\\Controller\\SpiceGirlsController:offer' => ['privates', '.service_locator.jigvWSH', 'get_ServiceLocator_JigvWSHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\SpiceGirlsController::add' => '?',
            'App\\Controller\\SpiceGirlsController::edit' => '?',
            'App\\Controller\\SpiceGirlsController::index' => '?',
            'App\\Controller\\SpiceGirlsController::offer' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\SpiceGirlsController:add' => '?',
            'App\\Controller\\SpiceGirlsController:edit' => '?',
            'App\\Controller\\SpiceGirlsController:index' => '?',
            'App\\Controller\\SpiceGirlsController:offer' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
