<?php

namespace ContainerHV3z5J9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JigvWSHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jigvWSH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jigvWSH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'offer' => ['privates', '.errored..service_locator.jigvWSH.App\\Entity\\Offers', NULL, 'Cannot autowire service ".service_locator.jigvWSH": it references class "App\\Entity\\Offers" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'offer' => 'App\\Entity\\Offers',
        ]);
    }
}
