# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = true
  config.vm.box_check_update = false
  
# config.vm.box = "generic/centos8"
  config.vm.box = "centos8_base"
  
  config.vm.provision "shell", path: "scripts/setup.sh"

end

