<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUy0Oza\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUy0Oza/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUy0Oza.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUy0Oza\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQUy0Oza\App_KernelDevDebugContainer([
    'container.build_hash' => 'QUy0Oza',
    'container.build_id' => '2bdc4348',
    'container.build_time' => 1607333046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUy0Oza');
