<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxPpx0K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxPpx0K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxPpx0K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxPpx0K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxPpx0K\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxPpx0K',
    'container.build_id' => 'd9706ce7',
    'container.build_time' => 1607174546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxPpx0K');
