<?php

namespace ContainerPxPpx0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CxDYfi9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CxDYfi9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CxDYfi9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offersRepository' => ['privates', 'App\\Repository\\OffersRepository', 'getOffersRepositoryService', true],
        ], [
            'offersRepository' => 'App\\Repository\\OffersRepository',
        ]);
    }
}
