<?php

namespace ContainerPxPpx0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jigvWSH.App\Entity\Offers' shared service.
     *
     * @return \App\Entity\Offers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jigvWSH": it references class "App\\Entity\\Offers" but no such service exists.');
    }
}
