<?php

namespace ContainerPxPpx0K;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpiceGirlsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SpiceGirlsController' shared autowired service.
     *
     * @return \App\Controller\SpiceGirlsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SpiceGirlsController.php';

        $container->services['App\\Controller\\SpiceGirlsController'] = $instance = new \App\Controller\SpiceGirlsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SpiceGirlsController', $container));

        return $instance;
    }
}
