# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://vagrantcloud.com/search.
 
  config.vm.box = "b2-tp3_systemd"
  
  config.vbguest.auto_update = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Exécution d'un script au démarrage de la VM
   config.vm.provision "shell", path: "script.sh"

 
  config.vm.define "node1" do |n1|
    n1.vm.network "private_network", ip: "192.168.2.21"
    n1.vm.hostname = "b2-tp3-systemd"
    
    n1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "VB_node1.centos7"
    end
  end 

 # config.vm.define "node2" do |n2|
 #   n2.vm.network "private_network", ip: "192.168.2.22"
 #   n2.vm.hostname = "node2.tp2.b2"
    
 #   n2.vm.provider "virtualbox" do |vb|
 #     vb.memory = "512"
 #     vb.name = "VB_node2.centos7"
 #   end
 # end

end
